openapi: 3.1.0
info:
    title: K24 API Contracts
    version: 1.0.0
   servers:
   paths:
    /api/users:
        get:
            summary: Fetch users list
            description: Returns a list of all users, or a filtered list by specified parameters
            parameters:
              - name: user_id
                in: query
                description: Unique, permanent ID of a user
                required: false
                schema:
                    type: integer
              - name: role
                in: query
                description: User's role in the system
                required: false
                schema:
                    type: string
            responses:
                '200':
                    description: List of users
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        user_id:
                                            type: integer
                                        role:
                                            type: string
                '500':
                    description: Failed to return users list
        post:
            summary: Create new user
            description: Creates a new user from role, assigns an ID and returns user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                role:
                                    type: string
            responses:
                '201':
                    description: Created user
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    user_id:
                                        type: integer
                                    role:
                                        type: string
                '400':
                    description: Failed to create user; invalid role?
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                '500':
                    description: Server failed to create user